
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry locationEntry;

	private global::Gtk.Label locationLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Wetter");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.locationEntry = new global::Gtk.Entry();
		this.locationEntry.WidthRequest = 273;
		this.locationEntry.CanFocus = true;
		this.locationEntry.Name = "locationEntry";
		this.locationEntry.IsEditable = true;
		this.locationEntry.InvisibleChar = '●';
		this.fixed1.Add(this.locationEntry);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.locationEntry]));
		w1.X = 230;
		w1.Y = 227;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.locationLabel = new global::Gtk.Label();
		this.locationLabel.Name = "locationLabel";
		this.locationLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Nach Stadt suchen");
		this.fixed1.Add(this.locationLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.locationLabel]));
		w2.X = 234;
		w2.Y = 205;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 799;
		this.DefaultHeight = 576;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.locationEntry.TextInserted += new global::Gtk.TextInsertedHandler(this.SearchLocation);
	}
}
